spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hofuri_cp
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  security: 
    user:
      name: keisuke
      password: baseball
    
  messages:
    basename: messages
    
  thymeleaf:
    mode: HTML
    
server:
  port: 8080